<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		DB::table('country')->delete();
		DB::table('country')->insert(array(
		  array('id' => '1','name' => 'Afghanistan','code' => 'AF','phone_code' => '93','iso3' => 'AFG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '2','name' => 'Albania','code' => 'AL','phone_code' => '355','iso3' => 'ALB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '3','name' => 'Algeria','code' => 'DZ','phone_code' => '213','iso3' => 'DZA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '4','name' => 'American Samoa','code' => 'AS','phone_code' => '1684','iso3' => 'ASM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '5','name' => 'Andorra','code' => 'AD','phone_code' => '376','iso3' => 'AND','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '6','name' => 'Angola','code' => 'AO','phone_code' => '244','iso3' => 'AGO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '7','name' => 'Anguilla','code' => 'AI','phone_code' => '1264','iso3' => 'AIA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '8','name' => 'Antarctica','code' => 'AQ','phone_code' => '0','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '9','name' => 'Antigua and Barbuda','code' => 'AG','phone_code' => '1268','iso3' => 'ATG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '10','name' => 'Argentina','code' => 'AR','phone_code' => '54','iso3' => 'ARG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '11','name' => 'Armenia','code' => 'AM','phone_code' => '374','iso3' => 'ARM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '12','name' => 'Aruba','code' => 'AW','phone_code' => '297','iso3' => 'ABW','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '13','name' => 'Australia','code' => 'AU','phone_code' => '61','iso3' => 'AUS','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '14','name' => 'Austria','code' => 'AT','phone_code' => '43','iso3' => 'AUT','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '15','name' => 'Azerbaijan','code' => 'AZ','phone_code' => '994','iso3' => 'AZE','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '16','name' => 'Bahamas','code' => 'BS','phone_code' => '1242','iso3' => 'BHS','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '17','name' => 'Bahrain','code' => 'BH','phone_code' => '973','iso3' => 'BHR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '18','name' => 'Bangladesh','code' => 'BD','phone_code' => '880','iso3' => 'BGD','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '19','name' => 'Barbados','code' => 'BB','phone_code' => '1246','iso3' => 'BRB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '20','name' => 'Belarus','code' => 'BY','phone_code' => '375','iso3' => 'BLR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '21','name' => 'Belgium','code' => 'BE','phone_code' => '32','iso3' => 'BEL','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '22','name' => 'Belize','code' => 'BZ','phone_code' => '501','iso3' => 'BLZ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '23','name' => 'Benin','code' => 'BJ','phone_code' => '229','iso3' => 'BEN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '24','name' => 'Bermuda','code' => 'BM','phone_code' => '1441','iso3' => 'BMU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '25','name' => 'Bhutan','code' => 'BT','phone_code' => '975','iso3' => 'BTN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '26','name' => 'Bolivia','code' => 'BO','phone_code' => '591','iso3' => 'BOL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '27','name' => 'Bosnia and Herzegovina','code' => 'BA','phone_code' => '387','iso3' => 'BIH','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '28','name' => 'Botswana','code' => 'BW','phone_code' => '267','iso3' => 'BWA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '29','name' => 'Bouvet Island','code' => 'BV','phone_code' => '0','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '30','name' => 'Brazil','code' => 'BR','phone_code' => '55','iso3' => 'BRA','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '31','name' => 'British Indian Ocean Territory','code' => 'IO','phone_code' => '246','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '32','name' => 'Brunei Darussalam','code' => 'BN','phone_code' => '673','iso3' => 'BRN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '33','name' => 'Bulgaria','code' => 'BG','phone_code' => '359','iso3' => 'BGR','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '34','name' => 'Burkina Faso','code' => 'BF','phone_code' => '226','iso3' => 'BFA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '35','name' => 'Burundi','code' => 'BI','phone_code' => '257','iso3' => 'BDI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '36','name' => 'Cambodia','code' => 'KH','phone_code' => '855','iso3' => 'KHM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '37','name' => 'Cameroon','code' => 'CM','phone_code' => '237','iso3' => 'CMR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '38','name' => 'Canada','code' => 'CA','phone_code' => '1','iso3' => 'CAN','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '39','name' => 'Cape Verde','code' => 'CV','phone_code' => '238','iso3' => 'CPV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '40','name' => 'Cayman Islands','code' => 'KY','phone_code' => '1345','iso3' => 'CYM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '41','name' => 'Central African Republic','code' => 'CF','phone_code' => '236','iso3' => 'CAF','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '42','name' => 'Chad','code' => 'TD','phone_code' => '235','iso3' => 'TCD','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '43','name' => 'Chile','code' => 'CL','phone_code' => '56','iso3' => 'CHL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '44','name' => 'China','code' => 'CN','phone_code' => '86','iso3' => 'CHN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '45','name' => 'Christmas Island','code' => 'CX','phone_code' => '61','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '46','name' => 'Cocos (Keeling) Islands','code' => 'CC','phone_code' => '672','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '47','name' => 'Colombia','code' => 'CO','phone_code' => '57','iso3' => 'COL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '48','name' => 'Comoros','code' => 'KM','phone_code' => '269','iso3' => 'COM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '49','name' => 'Congo','code' => 'CG','phone_code' => '242','iso3' => 'COG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '50','name' => 'Congo, the Democratic Republic of the','code' => 'CD','phone_code' => '242','iso3' => 'COD','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '51','name' => 'Cook Islands','code' => 'CK','phone_code' => '682','iso3' => 'COK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '52','name' => 'Costa Rica','code' => 'CR','phone_code' => '506','iso3' => 'CRI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '53','name' => 'Cote D\'Ivoire','code' => 'CI','phone_code' => '225','iso3' => 'CIV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '54','name' => 'Croatia','code' => 'HR','phone_code' => '385','iso3' => 'HRV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '55','name' => 'Cuba','code' => 'CU','phone_code' => '53','iso3' => 'CUB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '56','name' => 'Cyprus','code' => 'CY','phone_code' => '357','iso3' => 'CYP','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '57','name' => 'Czech Republic','code' => 'CZ','phone_code' => '420','iso3' => 'CZE','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '58','name' => 'Denmark','code' => 'DK','phone_code' => '45','iso3' => 'DNK','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '59','name' => 'Djibouti','code' => 'DJ','phone_code' => '253','iso3' => 'DJI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '60','name' => 'Dominica','code' => 'DM','phone_code' => '1767','iso3' => 'DMA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '61','name' => 'Dominican Republic','code' => 'DO','phone_code' => '1809','iso3' => 'DOM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '62','name' => 'Ecuador','code' => 'EC','phone_code' => '593','iso3' => 'ECU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '63','name' => 'Egypt','code' => 'EG','phone_code' => '20','iso3' => 'EGY','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '64','name' => 'El Salvador','code' => 'SV','phone_code' => '503','iso3' => 'SLV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '65','name' => 'Equatorial Guinea','code' => 'GQ','phone_code' => '240','iso3' => 'GNQ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '66','name' => 'Eritrea','code' => 'ER','phone_code' => '291','iso3' => 'ERI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '67','name' => 'Estonia','code' => 'EE','phone_code' => '372','iso3' => 'EST','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '68','name' => 'Ethiopia','code' => 'ET','phone_code' => '251','iso3' => 'ETH','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '69','name' => 'Falkland Islands (Malvinas)','code' => 'FK','phone_code' => '500','iso3' => 'FLK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '70','name' => 'Faroe Islands','code' => 'FO','phone_code' => '298','iso3' => 'FRO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '71','name' => 'Fiji','code' => 'FJ','phone_code' => '679','iso3' => 'FJI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '72','name' => 'Finland','code' => 'FI','phone_code' => '358','iso3' => 'FIN','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '73','name' => 'France','code' => 'FR','phone_code' => '33','iso3' => 'FRA','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '74','name' => 'French Guiana','code' => 'GF','phone_code' => '594','iso3' => 'GUF','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '75','name' => 'French Polynesia','code' => 'PF','phone_code' => '689','iso3' => 'PYF','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '76','name' => 'French Southern Territories','code' => 'TF','phone_code' => '0','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '77','name' => 'Gabon','code' => 'GA','phone_code' => '241','iso3' => 'GAB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '78','name' => 'Gambia','code' => 'GM','phone_code' => '220','iso3' => 'GMB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '79','name' => 'Georgia','code' => 'GE','phone_code' => '995','iso3' => 'GEO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '80','name' => 'Germany','code' => 'DE','phone_code' => '49','iso3' => 'DEU','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '81','name' => 'Ghana','code' => 'GH','phone_code' => '233','iso3' => 'GHA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '82','name' => 'Gibraltar','code' => 'GI','phone_code' => '350','iso3' => 'GIB','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '83','name' => 'Greece','code' => 'GR','phone_code' => '30','iso3' => 'GRC','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '84','name' => 'Greenland','code' => 'GL','phone_code' => '299','iso3' => 'GRL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '85','name' => 'Grenada','code' => 'GD','phone_code' => '1473','iso3' => 'GRD','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '86','name' => 'Guadeloupe','code' => 'GP','phone_code' => '590','iso3' => 'GLP','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '87','name' => 'Guam','code' => 'GU','phone_code' => '1671','iso3' => 'GUM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '88','name' => 'Guatemala','code' => 'GT','phone_code' => '502','iso3' => 'GTM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '89','name' => 'Guinea','code' => 'GN','phone_code' => '224','iso3' => 'GIN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '90','name' => 'Guinea-Bissau','code' => 'GW','phone_code' => '245','iso3' => 'GNB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '91','name' => 'Guyana','code' => 'GY','phone_code' => '592','iso3' => 'GUY','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '92','name' => 'Haiti','code' => 'HT','phone_code' => '509','iso3' => 'HTI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '93','name' => 'Heard Island and Mcdonald Islands','code' => 'HM','phone_code' => '0','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '94','name' => 'Holy See (Vatican City State)','code' => 'VA','phone_code' => '39','iso3' => 'VAT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '95','name' => 'Honduras','code' => 'HN','phone_code' => '504','iso3' => 'HND','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '96','name' => 'Hong Kong','code' => 'HK','phone_code' => '852','iso3' => 'HKG','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '97','name' => 'Hungary','code' => 'HU','phone_code' => '36','iso3' => 'HUN','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '98','name' => 'Iceland','code' => 'IS','phone_code' => '354','iso3' => 'ISL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '99','name' => 'India','code' => 'IN','phone_code' => '91','iso3' => 'IND','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '100','name' => 'Indonesia','code' => 'ID','phone_code' => '62','iso3' => 'IDN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '101','name' => 'Iran, Islamic Republic of','code' => 'IR','phone_code' => '98','iso3' => 'IRN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '102','name' => 'Iraq','code' => 'IQ','phone_code' => '964','iso3' => 'IRQ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '103','name' => 'Ireland','code' => 'IE','phone_code' => '353','iso3' => 'IRL','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '104','name' => 'Israel','code' => 'IL','phone_code' => '972','iso3' => 'ISR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '105','name' => 'Italy','code' => 'IT','phone_code' => '39','iso3' => 'ITA','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '106','name' => 'Jamaica','code' => 'JM','phone_code' => '1876','iso3' => 'JAM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '107','name' => 'Japan','code' => 'JP','phone_code' => '81','iso3' => 'JPN','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '108','name' => 'Jordan','code' => 'JO','phone_code' => '962','iso3' => 'JOR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '109','name' => 'Kazakhstan','code' => 'KZ','phone_code' => '7','iso3' => 'KAZ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '110','name' => 'Kenya','code' => 'KE','phone_code' => '254','iso3' => 'KEN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '111','name' => 'Kiribati','code' => 'KI','phone_code' => '686','iso3' => 'KIR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '112','name' => 'Korea, Democratic People\'s Republic of','code' => 'KP','phone_code' => '850','iso3' => 'PRK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '113','name' => 'Korea, Republic of','code' => 'KR','phone_code' => '82','iso3' => 'KOR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '114','name' => 'Kuwait','code' => 'KW','phone_code' => '965','iso3' => 'KWT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '115','name' => 'Kyrgyzstan','code' => 'KG','phone_code' => '996','iso3' => 'KGZ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '116','name' => 'Lao People\'s Democratic Republic','code' => 'LA','phone_code' => '856','iso3' => 'LAO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '117','name' => 'Latvia','code' => 'LV','phone_code' => '371','iso3' => 'LVA','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '118','name' => 'Lebanon','code' => 'LB','phone_code' => '961','iso3' => 'LBN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '119','name' => 'Lesotho','code' => 'LS','phone_code' => '266','iso3' => 'LSO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '120','name' => 'Liberia','code' => 'LR','phone_code' => '231','iso3' => 'LBR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '121','name' => 'Libyan Arab Jamahiriya','code' => 'LY','phone_code' => '218','iso3' => 'LBY','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '122','name' => 'Liechtenstein','code' => 'LI','phone_code' => '423','iso3' => 'LIE','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '123','name' => 'Lithuania','code' => 'LT','phone_code' => '370','iso3' => 'LTU','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '124','name' => 'Luxembourg','code' => 'LU','phone_code' => '352','iso3' => 'LUX','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '125','name' => 'Macao','code' => 'MO','phone_code' => '853','iso3' => 'MAC','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '126','name' => 'Macedonia, the Former Yugoslav Republic of','code' => 'MK','phone_code' => '389','iso3' => 'MKD','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '127','name' => 'Madagascar','code' => 'MG','phone_code' => '261','iso3' => 'MDG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '128','name' => 'Malawi','code' => 'MW','phone_code' => '265','iso3' => 'MWI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '129','name' => 'Malaysia','code' => 'MY','phone_code' => '60','iso3' => 'MYS','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '130','name' => 'Maldives','code' => 'MV','phone_code' => '960','iso3' => 'MDV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '131','name' => 'Mali','code' => 'ML','phone_code' => '223','iso3' => 'MLI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '132','name' => 'Malta','code' => 'MT','phone_code' => '356','iso3' => 'MLT','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '133','name' => 'Marshall Islands','code' => 'MH','phone_code' => '692','iso3' => 'MHL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '134','name' => 'Martinique','code' => 'MQ','phone_code' => '596','iso3' => 'MTQ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '135','name' => 'Mauritania','code' => 'MR','phone_code' => '222','iso3' => 'MRT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '136','name' => 'Mauritius','code' => 'MU','phone_code' => '230','iso3' => 'MUS','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '137','name' => 'Mayotte','code' => 'YT','phone_code' => '269','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '138','name' => 'Mexico','code' => 'MX','phone_code' => '52','iso3' => 'MEX','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '139','name' => 'Micronesia, Federated States of','code' => 'FM','phone_code' => '691','iso3' => 'FSM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '140','name' => 'Moldova, Republic of','code' => 'MD','phone_code' => '373','iso3' => 'MDA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '141','name' => 'Monaco','code' => 'MC','phone_code' => '377','iso3' => 'MCO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '142','name' => 'Mongolia','code' => 'MN','phone_code' => '976','iso3' => 'MNG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '143','name' => 'Montserrat','code' => 'MS','phone_code' => '1664','iso3' => 'MSR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '144','name' => 'Morocco','code' => 'MA','phone_code' => '212','iso3' => 'MAR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '145','name' => 'Mozambique','code' => 'MZ','phone_code' => '258','iso3' => 'MOZ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '146','name' => 'Myanmar','code' => 'MM','phone_code' => '95','iso3' => 'MMR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '147','name' => 'Namibia','code' => 'NA','phone_code' => '264','iso3' => 'NAM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '148','name' => 'Nauru','code' => 'NR','phone_code' => '674','iso3' => 'NRU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '149','name' => 'Nepal','code' => 'NP','phone_code' => '977','iso3' => 'NPL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '150','name' => 'Netherlands','code' => 'NL','phone_code' => '31','iso3' => 'NLD','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '151','name' => 'Netherlands Antilles','code' => 'AN','phone_code' => '599','iso3' => 'ANT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '152','name' => 'New Caledonia','code' => 'NC','phone_code' => '687','iso3' => 'NCL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '153','name' => 'New Zealand','code' => 'NZ','phone_code' => '64','iso3' => 'NZL','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '154','name' => 'Nicaragua','code' => 'NI','phone_code' => '505','iso3' => 'NIC','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '155','name' => 'Niger','code' => 'NE','phone_code' => '227','iso3' => 'NER','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '156','name' => 'Nigeria','code' => 'NG','phone_code' => '234','iso3' => 'NGA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '157','name' => 'Niue','code' => 'NU','phone_code' => '683','iso3' => 'NIU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '158','name' => 'Norfolk Island','code' => 'NF','phone_code' => '672','iso3' => 'NFK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '159','name' => 'Northern Mariana Islands','code' => 'MP','phone_code' => '1670','iso3' => 'MNP','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '160','name' => 'Norway','code' => 'NO','phone_code' => '47','iso3' => 'NOR','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '161','name' => 'Oman','code' => 'OM','phone_code' => '968','iso3' => 'OMN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '162','name' => 'Pakistan','code' => 'PK','phone_code' => '92','iso3' => 'PAK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '163','name' => 'Palau','code' => 'PW','phone_code' => '680','iso3' => 'PLW','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '164','name' => 'Palestinian Territory, Occupied','code' => 'PS','phone_code' => '970','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '165','name' => 'Panama','code' => 'PA','phone_code' => '507','iso3' => 'PAN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '166','name' => 'Papua New Guinea','code' => 'PG','phone_code' => '675','iso3' => 'PNG','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '167','name' => 'Paraguay','code' => 'PY','phone_code' => '595','iso3' => 'PRY','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '168','name' => 'Peru','code' => 'PE','phone_code' => '51','iso3' => 'PER','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '169','name' => 'Philippines','code' => 'PH','phone_code' => '63','iso3' => 'PHL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '170','name' => 'Pitcairn','code' => 'PN','phone_code' => '0','iso3' => 'PCN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '171','name' => 'Poland','code' => 'PL','phone_code' => '48','iso3' => 'POL','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '172','name' => 'Portugal','code' => 'PT','phone_code' => '351','iso3' => 'PRT','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '173','name' => 'Puerto Rico','code' => 'PR','phone_code' => '1787','iso3' => 'PRI','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '174','name' => 'Qatar','code' => 'QA','phone_code' => '974','iso3' => 'QAT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '175','name' => 'Reunion','code' => 'RE','phone_code' => '262','iso3' => 'REU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '176','name' => 'Romania','code' => 'RO','phone_code' => '40','iso3' => 'ROM','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '177','name' => 'Russian Federation','code' => 'RU','phone_code' => '70','iso3' => 'RUS','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '178','name' => 'Rwanda','code' => 'RW','phone_code' => '250','iso3' => 'RWA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '179','name' => 'Saint Helena','code' => 'SH','phone_code' => '290','iso3' => 'SHN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '180','name' => 'Saint Kitts and Nevis','code' => 'KN','phone_code' => '1869','iso3' => 'KNA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '181','name' => 'Saint Lucia','code' => 'LC','phone_code' => '1758','iso3' => 'LCA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '182','name' => 'Saint Pierre and Miquelon','code' => 'PM','phone_code' => '508','iso3' => 'SPM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '183','name' => 'Saint Vincent and the Grenadines','code' => 'VC','phone_code' => '1784','iso3' => 'VCT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '184','name' => 'Samoa','code' => 'WS','phone_code' => '684','iso3' => 'WSM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '185','name' => 'San Marino','code' => 'SM','phone_code' => '378','iso3' => 'SMR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '186','name' => 'Sao Tome and Principe','code' => 'ST','phone_code' => '239','iso3' => 'STP','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '187','name' => 'Saudi Arabia','code' => 'SA','phone_code' => '966','iso3' => 'SAU','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '188','name' => 'Senegal','code' => 'SN','phone_code' => '221','iso3' => 'SEN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '189','name' => 'Serbia and Montenegro','code' => 'RS','phone_code' => '381','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '190','name' => 'Seychelles','code' => 'SC','phone_code' => '248','iso3' => 'SYC','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '191','name' => 'Sierra Leone','code' => 'SL','phone_code' => '232','iso3' => 'SLE','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '192','name' => 'Singapore','code' => 'SG','phone_code' => '65','iso3' => 'SGP','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '193','name' => 'Slovakia','code' => 'SK','phone_code' => '421','iso3' => 'SVK','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '194','name' => 'Slovenia','code' => 'SI','phone_code' => '386','iso3' => 'SVN','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '195','name' => 'Solomon Islands','code' => 'SB','phone_code' => '677','iso3' => 'SLB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '196','name' => 'Somalia','code' => 'SO','phone_code' => '252','iso3' => 'SOM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '197','name' => 'South Africa','code' => 'ZA','phone_code' => '27','iso3' => 'ZAF','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '198','name' => 'South Georgia and the South Sandwich Islands','code' => 'GS','phone_code' => '0','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '199','name' => 'Spain','code' => 'ES','phone_code' => '34','iso3' => 'ESP','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '200','name' => 'Sri Lanka','code' => 'LK','phone_code' => '94','iso3' => 'LKA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '201','name' => 'Sudan','code' => 'SD','phone_code' => '249','iso3' => 'SDN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '202','name' => 'Suriname','code' => 'SR','phone_code' => '597','iso3' => 'SUR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '203','name' => 'Svalbard and Jan Mayen','code' => 'SJ','phone_code' => '47','iso3' => 'SJM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '204','name' => 'Swaziland','code' => 'SZ','phone_code' => '268','iso3' => 'SWZ','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '205','name' => 'Sweden','code' => 'SE','phone_code' => '46','iso3' => 'SWE','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '206','name' => 'Switzerland','code' => 'CH','phone_code' => '41','iso3' => 'CHE','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '207','name' => 'Syrian Arab Republic','code' => 'SY','phone_code' => '963','iso3' => 'SYR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '208','name' => 'Taiwan, Province of China','code' => 'TW','phone_code' => '886','iso3' => 'TWN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '209','name' => 'Tajikistan','code' => 'TJ','phone_code' => '992','iso3' => 'TJK','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '210','name' => 'Tanzania, United Republic of','code' => 'TZ','phone_code' => '255','iso3' => 'TZA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '211','name' => 'Thailand','code' => 'TH','phone_code' => '66','iso3' => 'THA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '212','name' => 'Timor-Leste','code' => 'TL','phone_code' => '670','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '213','name' => 'Togo','code' => 'TG','phone_code' => '228','iso3' => 'TGO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '214','name' => 'Tokelau','code' => 'TK','phone_code' => '690','iso3' => 'TKL','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '215','name' => 'Tonga','code' => 'TO','phone_code' => '676','iso3' => 'TON','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '216','name' => 'Trinidad and Tobago','code' => 'TT','phone_code' => '1868','iso3' => 'TTO','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '217','name' => 'Tunisia','code' => 'TN','phone_code' => '216','iso3' => 'TUN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '218','name' => 'Turkey','code' => 'TR','phone_code' => '90','iso3' => 'TUR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '219','name' => 'Turkmenistan','code' => 'TM','phone_code' => '7370','iso3' => 'TKM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '220','name' => 'Turks and Caicos Islands','code' => 'TC','phone_code' => '1649','iso3' => 'TCA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '221','name' => 'Tuvalu','code' => 'TV','phone_code' => '688','iso3' => 'TUV','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '222','name' => 'Uganda','code' => 'UG','phone_code' => '256','iso3' => 'UGA','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '223','name' => 'Ukraine','code' => 'UA','phone_code' => '380','iso3' => 'UKR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '224','name' => 'United Arab Emirates','code' => 'AE','phone_code' => '971','iso3' => 'ARE','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '225','name' => 'United Kingdom','code' => 'GB','phone_code' => '44','iso3' => 'GBR','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '226','name' => 'United States','code' => 'US','phone_code' => '1','iso3' => 'USA','status' => '1','stripe_country' => '1','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '227','name' => 'United States Minor Outlying Islands','code' => 'UM','phone_code' => '1','iso3' => NULL,'status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '228','name' => 'Uruguay','code' => 'UY','phone_code' => '598','iso3' => 'URY','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '229','name' => 'Uzbekistan','code' => 'UZ','phone_code' => '998','iso3' => 'UZB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '230','name' => 'Vanuatu','code' => 'VU','phone_code' => '678','iso3' => 'VUT','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '231','name' => 'Venezuela','code' => 'VE','phone_code' => '58','iso3' => 'VEN','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '232','name' => 'Viet Nam','code' => 'VN','phone_code' => '84','iso3' => 'VNM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '233','name' => 'Virgin Islands, British','code' => 'VG','phone_code' => '1284','iso3' => 'VGB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '234','name' => 'Virgin Islands, U.s.','code' => 'VI','phone_code' => '1340','iso3' => 'VIR','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '235','name' => 'Wallis and Futuna','code' => 'WF','phone_code' => '681','iso3' => 'WLF','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '236','name' => 'Western Sahara','code' => 'EH','phone_code' => '212','iso3' => 'ESH','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '237','name' => 'Yemen','code' => 'YE','phone_code' => '967','iso3' => 'YEM','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '238','name' => 'Zambia','code' => 'ZM','phone_code' => '260','iso3' => 'ZMB','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL),
		  array('id' => '239','name' => 'Zimbabwe','code' => 'ZW','phone_code' => '263','iso3' => 'ZWE','status' => '1','stripe_country' => '0','created_at' => NULL,'updated_at' => NULL)
		));
	}
}
